# -*- coding: utf-8 -*-
"""Copy of Exercícios da aula - Development with Python(1)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PlbtftnCnz6HETHd8Tuul6ceox53EZT4

# Development with Python — Aula 1
## 15 problemas de programação — nível moderado a difícil

Este notebook avalia exclusivamente os conceitos estudados na **Aula 1**.

### Conceitos permitidos

- lógica de programação;
- decomposição de problemas;
- algoritmos;
- variáveis e atribuição;
- `int`, `float`, `str`, `bool` e `None`;
- conversões básicas de tipos;
- operadores aritméticos;
- operadores relacionais;
- operadores lógicos;
- entrada e saída;
- `if`, `elif`, `else`;
- `for`;
- `while`;
- `range`;
- funções;
- parâmetros;
- argumentos;
- valores de retorno;
- escopo básico.

## Regras de implementação

As soluções devem ser construídas **somente com os conceitos acima**.

Não utilize:

- listas, tuplas, dicionários ou conjuntos;
- `import` ou bibliotecas;
- métodos de `str`;
- `break` ou `continue`;
- `try`/`except`;
- orientação a objetos;
- recursão;
- compreensões;
- `match`;
- funções prontas como `min`, `max`, `sum`, `sorted`, `reversed` ou `abs` para resolver a lógica principal;
- conversão para `str` quando o problema proibir explicitamente essa conversão.

Uma solução que funcione, mas utilize recursos fora do escopo, **não atende ao enunciado**.

## Como responder

Em cada problema há três partes obrigatórias:

1. **Previsão e decomposição:** escreva, em comentários, de 2 a 5 linhas explicando entradas, processamento e saída.
2. **Implementação:** escreva seu programa.
3. **Microdefesa:** responda, em comentários, à pergunta conceitual indicada.

Os casos de teste indicados fazem parte do enunciado. Seu programa deve funcionar para todos eles.

> Durante a correção, qualquer solução poderá ser acompanhada de uma explicação oral curta sobre uma linha, condição ou variável escolhida pelo professor.

---
# Problema 1 — Classificação da média nas fronteiras

**Nível:** Moderado


Um sistema acadêmico recebe três notas de um aluno.

Crie um programa que:

1. leia as três notas como `float`;
2. calcule a média aritmética;
3. classifique:
   - média menor que `4`: `Reprovado`;
   - média maior ou igual a `4` e menor que `6`: `Recuperação`;
   - média maior ou igual a `6` e menor que `9`: `Aprovado`;
   - média maior ou igual a `9`: `Aprovado com destaque`;
4. exiba a média com duas casas decimais e a classificação.

### Casos obrigatórios de teste

Sua lógica deve classificar corretamente médias exatamente iguais a:

- `4.0`
- `6.0`
- `9.0`

### Microdefesa

Explique em uma linha por que a ordem dos testes pode alterar o resultado.
"""

# ============================================================
# PROBLEMA 1
# ============================================================

# PREVISÃO E DECOMPOSIÇÃO
# Entrada(s):
nome = str(input("Dgigite o nome do aluno:  "))
nota1 = float(input("Digite a primeira nota:  "))
nota2 = float(input("Digite a segunda nota:   "))
nota3 = float(input("Digite a terça nota: "))
# Processamento:
media = (nota1 + nota2 + nota3) / 3

if media < 4:
  situacao = ("Reprovado")

elif media >= 4 and media < 6:
  situacao = ("Recuperação")

elif media >= 6 and media < 9:
  situacao = ("Aprovado")

elif media >= 9:
  situacao = ("Aprovado com destaque!!!")
# Saída:
print(f"A media do aluno {nome} foi {media}")
print(f"A situação é: {situacao}")

# IMPLEMENTAÇÃO


# MICRODEFESA: por que a ordem das condições pode alterar a classificação?
#

"""---
# Problema 2 — Ano bissexto: o caso 1900

**Nível:** Moderado


Receba um ano inteiro e informe:

`Bissexto`

ou

`Não bissexto`

Use exatamente estas regras:

- divisível por `400` → bissexto;
- divisível por `100`, mas não por `400` → não bissexto;
- divisível por `4`, mas não por `100` → bissexto;
- demais anos → não bissextos.

### Casos obrigatórios de teste

- `1900`
- `2000`
- `2024`
- `2100`

### Microdefesa

Explique por que apenas testar `ano % 4 == 0` produz uma resposta errada para pelo menos um dos casos obrigatórios.
"""

# ============================================================
# PROBLEMA 2
# ============================================================

# PREVISÃO E DECOMPOSIÇÃO
# Entrada(s):
ano = int(input("Digite o ano:  "))
# Processamento:
calculoPorQuatrocentos = ano % 400
calculoPorCem = ano % 100
calculoPorQuatro = ano % 4

if calculoPorQuatrocentos == 0:
  estatus = "Bissexto"

elif calculoPorCem == 0 and calculoPorQuatrocentos != 0:
  estatus = "Não é bissexto"

elif calculoPorQuatro == 0 and calculoPorCem != 0:
  estatus = "Bissexto"
# Saída:
print(f"O resultado é: {estatus}")

# IMPLEMENTAÇÃO


# MICRODEFESA: por que testar somente divisibilidade por 4 é insuficiente?
#

"""---
# Problema 3 — Maior e menor com empates parciais

**Nível:** Moderado/Difícil


Receba três números inteiros `a`, `b` e `c`.

O programa deve:

- informar `Todos iguais` se os três valores forem iguais;
- caso contrário, exibir o maior valor;
- exibir o menor valor.

### Atenção: empates parciais são válidos

Seu programa deve funcionar também para:

- `8, 8, 3`
- `4, 9, 9`
- `5, 2, 5`

### Restrição

Não utilize `min()` nem `max()`.

### Microdefesa

Explique por que testar apenas `a > b and a > c` não é suficiente para todos os casos.
"""

# ============================================================
# PROBLEMA 3
# ============================================================

# PREVISÃO E DECOMPOSIÇÃO
# Entrada(s):
a = int(input("Digite o número um:  "))
b = int(input("Digite o número dois:  "))
c = int(input("Digite o número tres:  "))
# Processamento:

if a == b == c:
   iguais = (a, b, c)
   print(f"O valores são: {iguais}")

elif a == b != c:
  parcial = (a, b, c)
  print(f"O valor parcial é {parcial}")

elif b == c != a:
  parcial = (a, b, c)
  print(f"O valor parcial é {parcial}")

elif c == a != b:
  parcial = (a, b, c)
  print(f"O valor parcial é {parcial}")

else:
  if a >= b and a >= c:
    maior = (a)
    print(f"O maior número é: {maior}")

  elif b >= a and b >= c:
    maior = (b)
    print(f"O maior número é: {maior}")

  else:
    maior = (c)
    print(f"O maior número é: {maior}")

  if a <= b and a <= c:
    menor = (a)
    print(f"O menor número é: {menor}")

  elif b <= a and b <= c:
    menor = (b)
    print(f"O menor número é: {menor}")

  else:
    menor = (c)
    print(f"O menor número é: {menor}")



# Saída:


# IMPLEMENTAÇÃO


# MICRODEFESA: o que muda quando dois valores máximos ou mínimos são iguais?
#

"""---
# Problema 4 — Intervalo e paridade

**Nível:** Moderado


Receba um número inteiro.

Calcule três valores booleanos:

1. se o número está entre `10` e `50`, inclusive;
2. se é par;
3. se atende às duas condições ao mesmo tempo.

Exiba:

`Está no intervalo: True/False`

`É par: True/False`

`Atende às duas regras: True/False`

### Casos obrigatórios de teste

- `10`
- `50`
- `9`
- `51`
- `11`

### Microdefesa

Explique a diferença entre usar `and` e `or` na terceira regra.
"""

# ============================================================
# PROBLEMA 4
# ============================================================

# PREVISÃO E DECOMPOSIÇÃO
# Entrada(s):
numero = int(input("Digite um número: "))
intervalo = numero >= 10 and numero <=50
par = (numero % 2) == 0

a = True
b = False

# Processamento:
if intervalo:
  print(f"Está no intervalo:  {a}")

else:
  print(f"Está no intervalo:  {b}")

if par:
  print(f"É par:  {a}")

else:
  print(f"É par:  {b}")


if intervalo and par:
  print(f"Atende às duas regras:  {a}")


else:
  print(f"Atende às duas regras:  {b}")



# Saída:
#

# IMPLEMENTAÇÃO


# MICRODEFESA: qual seria o erro lógico se a terceira regra usasse or?
# Porque no OR as duas condições poderiam ser verdadeiras também e aqui o
# o sistame quer apenas uma condição verdadeira.

"""---
# Problema 5 — Contagem regressiva seletiva

**Nível:** Moderado


Receba um inteiro `n` maior ou igual a `0`.

Utilizando **somente `while` para a repetição**, exiba os números de `n` até `0`.

Quando o valor atual for:

- maior que `0`;
- e divisível por `5`;

exiba:

`X é divisível por 5`

nos demais casos, exiba apenas o número.

### Casos obrigatórios de teste

- `n = 0`
- `n = 1`
- `n = 5`
- `n = 10`

### Microdefesa

Identifique qual atribuição faz o laço se aproximar da condição de término.
"""

# ============================================================
# PROBLEMA 5
# ============================================================

# PREVISÃO E DECOMPOSIÇÃO
# Entrada(s):
x = int(input("Digite um número:  "))
calculo = (x % 5) == 0 or (x % 5) == 5

#conta = (x / 5) == 0 or 5
# Processamento:

while x >= 0:
  if x > 0 and calculo:
    print("X é divisível por 5")
    break

  else:
    print(x)
    x -= 1


# Saída:
#

# IMPLEMENTAÇÃO


# MICRODEFESA: qual linha garante que o while possa terminar?
# a linha que tem essa atribuição aqui (x -= 1)

"""---
# Problema 6 — Soma de múltiplos sem divisor zero

**Nível:** Moderado


Receba:

- `limite`, inteiro maior ou igual a `1`;
- `divisor`, inteiro diferente de `0`.

Some todos os inteiros de `1` até `limite`, inclusive, que sejam divisíveis por `divisor`.

### Exemplo

Para `limite = 10` e `divisor = 3`:

`3 + 6 + 9 = 18`

### Restrições

- utilize `for` e `range`;
- não utilize `sum()`.

### Casos obrigatórios de teste

- `limite = 10`, `divisor = 3`
- `limite = 5`, `divisor = 7`
- `limite = 6`, `divisor = 2`

### Microdefesa

Explique por que o acumulador deve possuir um valor inicial antes do `for`.
"""

# ============================================================
# PROBLEMA 6
# ============================================================

# PREVISÃO E DECOMPOSIÇÃO
# Entrada(s):
limite = int(input("Digite o valor do limite: "))
divisor = int(input("Digite um número para o divisor: "))

soma = 0
for i in range(1, limite + 1):
  if (i % divisor) == 0:
    soma += i
    print(i)
print(f"A soma é: {soma}")






# Processamento:
#soma = 0


# Saída:
#

# IMPLEMENTAÇÃO


# MICRODEFESA: por que o acumulador precisa ser inicializado?
# Porque ele armazena o resultado de uma conta ate chegar no resultado final.

"""---
# Problema 7 — Fatorial e os casos 0! e 1!

**Nível:** Moderado/Difícil


Receba um inteiro `n` maior ou igual a `0` e calcule `n!`.

Considere:

- `0! = 1`
- `1! = 1`
- `5! = 120`

### Restrições

- use repetição;
- não utilize bibliotecas;
- não utilize função pronta de fatorial.

### Casos obrigatórios de teste

- `0`
- `1`
- `5`
- `6`

### Microdefesa

Explique por que iniciar o acumulador em `0` destruiria o cálculo.
"""

# ============================================================
# PROBLEMA 7
# ============================================================

# PREVISÃO E DECOMPOSIÇÃO
# Entrada(s):
#
# Processamento:
#
# Saída:
#

# IMPLEMENTAÇÃO


# MICRODEFESA: por que o acumulador do produto deve começar em 1?
#

"""---
# Problema 8 — Sequência definida por passo

**Nível:** Moderado/Difícil


Receba três inteiros:

- `inicio`;
- `passo`;
- `quantidade`, maior ou igual a `1`.

Exiba exatamente `quantidade` valores.

O primeiro valor é `inicio`. Cada valor seguinte é obtido somando `passo` ao anterior.

### Exemplos obrigatórios

`inicio = 4`, `passo = 3`, `quantidade = 5`

deve produzir:

`4, 7, 10, 13, 16`

E:

`inicio = 5`, `passo = -2`, `quantidade = 4`

deve produzir:

`5, 3, 1, -1`

### Restrição

Não armazene a sequência em uma coleção.

### Microdefesa

Explique por que `quantidade` controla o número de repetições, e não o valor final da sequência.
"""

# ============================================================
# PROBLEMA 8
# ============================================================

# PREVISÃO E DECOMPOSIÇÃO
# Entrada(s):

# Processamento:
#
# Saída:
#

# IMPLEMENTAÇÃO


# MICRODEFESA: por que quantidade não pode ser usada como limite numérico da sequência?
#

"""---
# Problema 9 — Número primo sem interrupção antecipada

**Nível:** Difícil


Receba um inteiro `n` maior que `1`.

Determine se ele é primo contando seus divisores positivos.

Um número primo possui exatamente dois divisores positivos.

### Restrições

- utilize repetição;
- não utilize `break`;
- não utilize bibliotecas.

### Casos obrigatórios de teste

- `2`
- `3`
- `4`
- `9`
- `17`
- `25`

### Microdefesa

Explique por que `1` e o próprio número precisam participar da contagem se sua regra é “exatamente dois divisores”.
"""

# ============================================================
# PROBLEMA 9
# ============================================================

# PREVISÃO E DECOMPOSIÇÃO
# Entrada(s):
#
# Processamento:
#
# Saída:
#

# IMPLEMENTAÇÃO


# MICRODEFESA: quais são os dois divisores de um número primo?
#

"""---
# Problema 10 — Função de classificação numérica

**Nível:** Moderado


Crie a função:

`classificar_numero(numero)`

Ela deve retornar exatamente uma das strings:

- `positivo e par`
- `positivo e ímpar`
- `negativo e par`
- `negativo e ímpar`
- `zero`

Depois:

1. leia um inteiro;
2. passe-o como argumento;
3. armazene o retorno;
4. exiba o resultado.

### Casos obrigatórios de teste

- `-4`
- `-3`
- `0`
- `2`
- `5`

### Microdefesa

Explique por que `0` merece uma decisão própria antes de classificá-lo como positivo ou negativo.
"""

# ============================================================
# PROBLEMA 10
# ============================================================
def classificar_numero():
# PREVISÃO E DECOMPOSIÇÃO
# Entrada(s):
  numero = int(input("Digite um numero: "))
# Processamento:

  if numero > 0 and (numero % 2) == 0:
    print("positivo e par")

  elif numero > 0 and (numero % 2) == 1:
    print("positivo e impar")

  else:
    if numero < 0 and (numero % 2) == 0:
      print("negativo e par")

    elif numero < 0 and (numero % 2) == 1:
      print("negativo e impar")

    else:
      if numero == 0:
        print("Zero")




# IMPLEMENTAÇÃO
classificar_numero()
# MICRODEFESA: por que zero não deve cair nas categorias positivo/negativo?
# Porque o ZERO é um número neutro.

"""---
# Problema 11 — Calculadora e retorno None

**Nível:** Moderado/Difícil


Crie:

`calcular(a, b, operacao)`

`operacao` será uma `str` contendo exatamente um destes símbolos:

- `+`
- `-`
- `*`
- `/`

A função deve:

- retornar o resultado da operação válida;
- retornar `None` se a operação não for reconhecida;
- retornar `None` se houver tentativa de divisão por zero.

Depois, o programa deve exibir:

`Operação inválida`

quando o retorno for `None`.

### Casos obrigatórios de teste

- `10, 2, "+"`
- `10, 2, "/"`
- `10, 0, "/"`
- `10, 2, "x"`

### Microdefesa

Explique a diferença entre imprimir o resultado dentro da função e retorná-lo.
"""

from binascii import b2a_qp
# ============================================================
# PROBLEMA 11
# ============================================================

# PREVISÃO E DECOMPOSIÇÃO
# Entrada(s):
def calcular():

  a = int(input("Digite o primeiro número:  "))
  b = int(input("Digite o segundo número: "))
  operacao = input("Escolha um operador(+, -, *, /):  ")

  if operacao == "+":
    calculo = a + b

  elif operacao == "-":
    calculo = a - b

  elif operacao == "*":
    calculo = a * b

  elif operacao == "/":
    if b == 0:
      return "Divisão por zero."
    calculo = a / b

  else:
    print("Tente novamente. Digite números inteiros e algum operar para realizar o calculo.")



# Processamento:
#
# Saída:
  print(f"O resultado da sua operação é: {calculo}")

# IMPLEMENTAÇÃO

calcular()
# MICRODEFESA: por que print dentro da função não substitui return?
# Porque o print apenas imprime o resultado, enquanto o return retorna um
# resultado.

"""---
# Problema 12 — Potência por multiplicações sucessivas

**Nível:** Difícil


Crie:

`potencia(base, expoente)`

A função deve calcular a potência usando multiplicações sucessivas.

Considere `expoente` inteiro maior ou igual a `0`.

### Restrições

- não utilize `**`;
- não utilize bibliotecas.

### Casos obrigatórios de teste

- `potencia(2, 4)` → `16`
- `potencia(5, 0)` → `1`
- `potencia(-2, 3)` → `-8`
- `potencia(-2, 4)` → `16`

### Microdefesa

Explique por que o resultado inicial precisa ser `1`, especialmente quando o expoente é `0`.
"""

# ============================================================
# PROBLEMA 12
# ============================================================

# PREVISÃO E DECOMPOSIÇÃO
# Entrada(s):
#
# Processamento:
#
# Saída:
#

# IMPLEMENTAÇÃO


# MICRODEFESA: por que iniciar resultado em 1 resolve também expoente zero?
#

"""---
# Problema 13 — Soma dos dígitos sem str

**Nível:** Difícil


Receba um inteiro positivo e calcule a soma de seus dígitos **sem converter o número para `str`**.

### Exemplo

`5832` → `5 + 8 + 3 + 2` → `18`

### Restrições

- não utilize `str`;
- não utilize coleções;
- não utilize métodos de string;
- utilize operações aritméticas e repetição.

### Casos obrigatórios de teste

- `10` → `1`
- `999` → `27`
- `1001` → `2`
- `5832` → `18`

### Microdefesa

Explique o papel de `% 10` e de `// 10` no algoritmo.
"""

# ============================================================
# PROBLEMA 13
# ============================================================

# PREVISÃO E DECOMPOSIÇÃO
# Entrada(s):

numero = int(input("Digite alguns números: "))
soma = 0

# Processamento:

while numero != 0:

  extrair = numero % 10
  soma += extrair
  retirar = numero // 10
  numero = retirar

# Saída:

print(f"A soma é: {soma}")

# IMPLEMENTAÇÃO


# MICRODEFESA: o que % 10 extrai e o que // 10 remove?

"""---
# Problema 14 — Inversão numérica e zeros à direita

**Nível:** Difícil


Receba um inteiro positivo e produza outro inteiro com seus dígitos invertidos.

### Exemplos

`4721` → `1274`

`1200` → `21`

O segundo resultado é `21`, e não `0021`, porque o resultado deve ser um inteiro.

### Restrições

- não converta para `str`;
- não utilize coleções;
- utilize operações aritméticas e repetição.

### Casos obrigatórios de teste

- `4721`
- `1200`
- `7`
- `1001`

### Microdefesa

Explique por que os zeros que aparecem à esquerda do valor invertido não permanecem na representação inteira.
"""

# ============================================================
# PROBLEMA 14
# ============================================================

# PREVISÃO E DECOMPOSIÇÃO
# Entrada(s):
#
# Processamento:
#
# Saída:
#

# IMPLEMENTAÇÃO


# MICRODEFESA: por que 1200 invertido numericamente resulta em 21?
#

"""---
# Problema 15 — Palíndromo preservando o valor original

**Nível:** Difícil


Um inteiro é palíndromo quando possui o mesmo valor quando seus dígitos são lidos nas duas direções.

Crie:

`eh_palindromo(numero)`

A função deve:

1. receber um inteiro positivo;
2. preservar o valor original;
3. construir numericamente o valor invertido;
4. comparar invertido e original;
5. retornar `True` ou `False`.

Depois, exiba:

`Palíndromo`

ou

`Não palíndromo`

### Restrições

- não utilize `str`;
- não utilize coleções;
- não utilize bibliotecas.

### Casos obrigatórios de teste

- `121` → palíndromo
- `1331` → palíndromo
- `1234` → não palíndromo
- `10` → não palíndromo
- `1001` → palíndromo

### Microdefesa

Explique por que modificar diretamente o único valor de `numero` durante a inversão pode impedir a comparação final correta.
"""

# ============================================================
# PROBLEMA 15
# ============================================================

# PREVISÃO E DECOMPOSIÇÃO
# Entrada(s):
#
# Processamento:
#
# Saída:
#

# IMPLEMENTAÇÃO


# MICRODEFESA: qual valor precisa ser preservado e por quê?
#

"""---
# Auditoria final da própria solução

Antes de entregar, confirme:

- [ ] usei apenas conceitos da Aula 1;
- [ ] não utilizei `import`;
- [ ] não utilizei listas, tuplas, dicionários ou conjuntos;
- [ ] não utilizei `break`, `continue`, `try`, `match` ou recursão;
- [ ] não utilizei `min`, `max`, `sum`, `sorted`, `reversed` ou `abs` para resolver a lógica;
- [ ] respeitei as proibições específicas de `str` dos problemas 13, 14 e 15;
- [ ] testei todos os casos obrigatórios;
- [ ] consigo explicar cada condição e cada variável que escrevi;
- [ ] consigo explicar por que meu `while` termina;
- [ ] consigo explicar o valor inicial de cada acumulador;
- [ ] consigo explicar o que minha função recebe e o que retorna.

## Importante

Uma saída correta para apenas um exemplo não prova que o algoritmo está correto.

A avaliação considera:

1. aderência ao enunciado;
2. correção nos casos-limite;
3. uso exclusivo dos conceitos estudados;
4. capacidade de explicar a própria solução.
"""